export const LocationImg = [
  {
    id: 1,
    image: "https://source.unsplash.com/collection/190727/300x300",
    alt: "Image for location x 1",
    ARLink: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },
  {
    id: 2,
    image: "https://source.unsplash.com/user/atlasior/300x300",
    alt: "Image for location x 2",
    ARLink: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },
  {
    id: 3,
    image: "https://source.unsplash.com/user/beataratuszniak/300x300",
    alt: "Image for location x 3",
    ARLink: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },
  {
    id: 4,
    image: "https://source.unsplash.com/user/beataratuszniak/300x300",
    alt: "Image for location x 4",
    ARLink: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },
  {
    id: 5,
    image: "https://source.unsplash.com/user/erondu/600x600",
    alt: "Image for location x 5",
    ARLink: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },
  {
    id: 6,
    image: "https://source.unsplash.com/user/erondu/600x600",
    alt: "Image for location x 6",
    alt: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },
  {
    id: 7,
    image: "https://source.unsplash.com/user/joannecaselynsuarez/300x300",
    alt: "Image for location x 7",
    ARLink: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },
  {
    id: 8,
    image: "https://source.unsplash.com/user/joannecaselynsuarez/300x300",
    alt: "Image for location x 8",
    ARLink: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },
  {
    id: 9,
    image: "https://source.unsplash.com/user/liamsimpson/600x600",
    alt: "Image for location x 9",
    ARLink: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },
  {
    id: 10,
    image: "https://source.unsplash.com/user/liamsimpson/600x600",
    alt: "Image for location x 10",
    ARLink: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },
  {
    id: 11,
    image: "https://source.unsplash.com/user/randomlies/300x300",
    alt: "Image for location x 11",
    ARLink: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },
  {
    id: 12,
    image: "https://source.unsplash.com/user/randomlies/600x600",
    alt: "Image for location x 12",
    ARLink: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },
  {
    id: 13,
    image: "https://source.unsplash.com/user/rawpixel/300x300",
    alt: "Image for location x 13",
    ARLink: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },
  {
    id: 14,
    image: "https://source.unsplash.com/user/stephanvancephoto/300x300",
    alt: "Image for location x 14",
    ARLink: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },
  {
    id: 15,
    image: "https://source.unsplash.com/user/stephanvancephoto/300x300",
    alt: "Image for location x 15",
    ARLink: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },
  {
    id: 16,
    image: "https://source.unsplash.com/user/timmarshall/300x300",
    alt: "Image for location x 16",
    ARLink: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },
  {
    id: 17,
    image: "https://source.unsplash.com/user/timmarshall/300x300",
    alt: "Image for location x 17",
    ARLink: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },
  {
    id: 18,
    image: "https://source.unsplash.com/user/tonill/300x300",
    alt: "Image for location x 18",
    ARLink: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },
  {
    id: 19,
    image: "https://source.unsplash.com/user/tonill/300x300",
    alt: "Image for location x 19",
    ARLink: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },

  {
    id: 20,
    image: "https://source.unsplash.com/user/tonill/300x300",
    alt: "Image for location x 20",
    ARLink: "https://bob5r5.csb.app",
    postcode: "BN23 1ED",
  },
];
