/* .map()
    id: 1,
    FirstName_LastName_UK: "Michael Nihell Bovell",
    people_enslaved: 158,
    compensation: 838,    £
    latitude: 50.813492,
    longitude: -0.372458,
*/

export const locationData = [
  {
    id: 1,
    FirstName_LastName_UK: "Michael Nihell Bovell",
    city_UK: "Worthing",
    Island: "British Guiana:",
    people_enslaved: 158,
    compensation: 838,
    latitude: 50.813492,
    longitude: -0.372458,
  },
  {
    id: 2,
    FirstName_LastName_UK: "Michael Nihell Bovell",
    city_UK: "Worthing",
    Island: "British Guiana:",
    people_enslaved: 11,
    compensation: 492,
    latitude: 50.813492,
    longitude: -0.372458,
  },
  //   {
  //     id: 3,
  //     FirstName_LastName_UK: "Michael Nihell Bovell",
  //     city_UK: "Worthing",
  //     Island: "British Guiana:",
  //     people_enslaved: 225,
  //     compensation: 11944,
  //     latitude: 50.813492,
  //     longitude: -0.372458,
  //   },
  {
    id: 4,
    FirstName_LastName_UK: "William Bryan",
    city_UK: "Worthing",
    Island: "No Island",
    people_enslaved: "n/a",
    compensation: "No Comp",
    latitude: 50.8179,
    longitude: -0.3729,
  },
  //   {
  //     id: 5,
  //     FirstName_LastName_UK: "William / Catherine Carter (nee Hayne)",
  //     city_UK: "Worthing",
  //     Island: "Jamaica",
  //     people_enslaved: 82,
  //     compensation: 1712,
  //     latitude: 50.8179,
  //     longitude: -0.3729,
  //   },
  //   {
  //     id: 6,
  //     FirstName_LastName_UK: "William Carter",
  //     city_UK: "Worthing",
  //     Island: "Jamaica",
  //     people_enslaved: 5,
  //     compensation: 107,
  //     latitude: 50.8179,
  //     longitude: -0.3729,
  //   },
  //   {
  //     id: 7,
  //     FirstName_LastName_UK: "Charles Beckford Long",
  //     city_UK: "Worthing",
  //     Island: "Jamaica",
  //     people_enslaved: 233,
  //     compensation: 3979,
  //     latitude: 50.8179,
  //     longitude: -0.3729,
  //   },
  //   {
  //     id: 8,
  //     FirstName_LastName_UK: "Charles Beckford Long",
  //     city_UK: "Worthing",
  //     Island: "Jamaica",
  //     people_enslaved: 1,
  //     compensation: 12,
  //     latitude: 50.8179,
  //     longitude: -0.3729,
  //   },
  //   {
  //     id: 9,
  //     FirstName_LastName_UK: "David Lyon Junior",
  //     city_UK: "Worthing",
  //     Island: "Jamaica",
  //     people_enslaved: 310,
  //     compensation: 5622,
  //     latitude: 50.811389,
  //     longitude: -0.431813,
  //   },
  {
    id: 10,
    FirstName_LastName_UK: "David Lyon Junior",
    city_UK: "Worthing",
    Island: "Jamaica",
    people_enslaved: 174,
    compensation: 3425,
    latitude: 50.811389,
    longitude: -0.431823,
  },
  //   {
  //     id: 11,
  //     FirstName_LastName_UK: "David Lyon Junior",
  //     city_UK: "Worthing",
  //     Island: "Jamaica",
  //     people_enslaved: 143,
  //     compensation: 3070,
  //     latitude: 50.811389,
  //     longitude: -0.431833,
  //   },
  //   {
  //     id: 12,
  //     FirstName_LastName_UK: "David Lyon Junior",
  //     city_UK: "Worthing",
  //     Island: "Jamaica",
  //     people_enslaved: 146,
  //     compensation: 2996,
  //     latitude: 50.811389,
  //     longitude: -0.431843,
  //   },
  //   {
  //     id: 13,
  //     FirstName_LastName_UK: "David Lyon Junior",
  //     city_UK: "Worthing",
  //     Island: "Jamaica",
  //     people_enslaved: 325,
  //     compensation: 5866,
  //     latitude: 50.811389,
  //     longitude: -0.431853,
  //   },
  //   {
  //     id: 14,
  //     FirstName_LastName_UK: "David Lyon Junior",
  //     city_UK: "Worthing",
  //     Island: "Jamaica",
  //     people_enslaved: 304,
  //     compensation: 5417,
  //     latitude: 50.811389,
  //     longitude: -0.431863,
  //   },
  //   {
  //     id: 15,
  //     FirstName_LastName_UK: "David Lyon Junior",
  //     city_UK: "Worthing",
  //     Island: "Jamaica",
  //     people_enslaved: 103,
  //     compensation: 1855,
  //     latitude: 50.811389,
  //     longitude: -0.431873,
  //   },
  //   {
  //     id: 16,
  //     FirstName_LastName_UK: "David Lyon Junior",
  //     city_UK: "Worthing",
  //     Island: "Jamaica",
  //     people_enslaved: 207,
  //     compensation: 2755,
  //     latitude: 50.811389,
  //     longitude: -0.431883,
  //   },
  //   {
  //     id: 17,
  //     FirstName_LastName_UK: "David Lyon Junior",
  //     city_UK: "Worthing",
  //     Island: "Jamaica",
  //     people_enslaved: 269,
  //     compensation: 4583,
  //     latitude: 50.811389,
  //     longitude: -0.431893,
  //   },
  //   {
  //     id: 18,
  //     FirstName_LastName_UK: "David Lyon Junior",
  //     city_UK: "Worthing",
  //     Island: "Jamaica",
  //     people_enslaved: 191,
  //     compensation: 3574,
  //     latitude: 50.811389,
  //     longitude: -0.431895,
  //   },
  //   {
  //     id: 19,
  //     FirstName_LastName_UK: "David Lyon Junior",
  //     city_UK: "Worthing",
  //     Island: "Jamaica",
  //     people_enslaved: 143,
  //     compensation: 2839,
  //     latitude: 50.811389,
  //     longitude: -0.431898,
  //   },
  //   {
  //     id: 20,
  //     FirstName_LastName_UK: "David Lyon Junior",
  //     city_UK: "Worthing",
  //     Island: "Jamaica",
  //     people_enslaved: 146,
  //     compensation: 2727,
  //     latitude: 50.811389,
  //     longitude: -0.431899,
  //   },
  //   {
  //     id: 21,
  //     FirstName_LastName_UK: "David Lyon Junior",
  //     city_UK: "Worthing",
  //     Island: "Jamaica",
  //     people_enslaved: 118,
  //     compensation: 2125,
  //     latitude: 50.811389,
  //     longitude: -0.4318995,
  //   },
  //   {
  //     id: 22,
  //     FirstName_LastName_UK: "william Nedham",
  //     city_UK: "Worthing",
  //     Island: "Jamaica",
  //     people_enslaved: 194,
  //     compensation: 3669,
  //     latitude: 50.810706,
  //     longitude: -0.364391,
  //   },
  //   {
  //     id: 22,
  //     FirstName_LastName_UK: "Kenrick Francis Saunders ",
  //     city_UK: "Brighton",
  //     Island: "Barbados",
  //     people_enslaved: 164,
  //     compensation: 3577,
  //     latitude: 50.827716,
  //     longitude: -0.141673,
  //   },
  //   {
  //     id: 23,
  //     FirstName_LastName_UK: "Ann Napier (née Stirling) ",
  //     city_UK: "Brighton",
  //     Island: "Tobago 58 (Merchiston)",
  //     people_enslaved: 123,
  //     compensation: 2576,
  //     latitude: 50.826033,
  //     longitude: -0.142296,
  //   },
  //   {
  //     id: 24,
  //     FirstName_LastName_UK: "Anna Elizabeth Anderson ",
  //     city_UK: "Brighton",
  //     Island: "Vigin Iislands 219",
  //     people_enslaved: 160,
  //     compensation: 1111,
  //     latitude: 50.8289,
  //     longitude: -0.141,
  //   },
  //   {
  //     id: 25,
  //     FirstName_LastName_UK: "Caroline Atkinson Swaby ",
  //     city_UK: "Brighton",
  //     Island: "Jamaica",
  //     people_enslaved: 453,
  //     compensation: 8633,
  //     latitude: 50.8216405,
  //     longitude: -0.1308382,
  //   },
  //   {
  //     id: 26,
  //     FirstName_LastName_UK: "Caroline Ellen Anderson ",
  //     city_UK: "Brighton",
  //     Island: "Vigin Iislands",
  //     people_enslaved: 160,
  //     compensation: 1111,
  //     latitude: 50.8191049,
  //     longitude: -0.1266938,
  //   },
  //   {
  //     id: 27,
  //     FirstName_LastName_UK: "Catherine Wratislaw (née Barry) ",
  //     city_UK: "Brighton",
  //     Island: "British Guiana",
  //     people_enslaved: 108,
  //     compensation: 5813,
  //     latitude: 50.827995,
  //     longitude: -0.141479,
  //   },
  //   {
  //     id: 28,
  //     FirstName_LastName_UK: "Cecilia Blake ",
  //     city_UK: "Brighton",
  //     Island: "St Vincent",
  //     people_enslaved: 188,
  //     compensation: 5052,
  //     latitude: 50.822158,
  //     longitude: -0.144199,
  //   },
  //   {
  //     id: 29,
  //     FirstName_LastName_UK: "Charles Lushington ",
  //     city_UK: "Brighton",
  //     Island: "Jamaica",
  //     people_enslaved: 332,
  //     compensation: 5849,
  //     latitude: 50.8198085,
  //     longitude: -0.1355206,
  //   },
  //   {
  //     id: 30,
  //     FirstName_LastName_UK: "Cornelius Paine ",
  //     city_UK: "Brighton",
  //     Island: "Montserrat",
  //     people_enslaved: 323,
  //     compensation: 5061,
  //     latitude: 50.8163271,
  //     longitude: -0.1121712,
  //   },
  //   {
  //     id: 31,
  //     FirstName_LastName_UK: "Edward Hoare ",
  //     city_UK: "Brighton",
  //     Island: "Jamaica",
  //     people_enslaved: 998,
  //     compensation: 19400,
  //     latitude: 50.8242199,
  //     longitude: -0.14481,
  //   },
  //   {
  //     id: 32,
  //     FirstName_LastName_UK: "Edward Monk",
  //     city_UK: "Cliffe",
  //     Island: "Antigua",
  //     people_enslaved: 55,
  //     compensation: 800,
  //     latitude: 50.8736115,
  //     longitude: 0.0192103,
  //   },
  //   {
  //     id: 33,
  //     FirstName_LastName_UK: "George Monk ",
  //     city_UK: "Brighton",
  //     Island: "Antigua",
  //     people_enslaved: 55,
  //     compensation: "n/d",
  //     latitude: 50.822681,
  //     longitude: -0.14408,
  //   },
  //   {
  //     id: 34,
  //     FirstName_LastName_UK: "George Washington Philips& Edward Lumley Wilson ",
  //     city_UK: "Brighton",
  //     Island: "St Kits",
  //     people_enslaved: 161,
  //     compensation: 2678,
  //     latitude: 50.819691,
  //     longitude: -0.13322128,
  //   },
  //   {
  //     id: 35,
  //     FirstName_LastName_UK: "Georgina Frances de Peyronnet (née Whitfield) ",
  //     city_UK: "Brighton",
  //     Island: "Grenada",
  //     people_enslaved: 337,
  //     compensation: 11279,
  //     latitude: 50.819733,
  //     longitude: -0.133217,
  //   },
  //   {
  //     id: 36,
  //     FirstName_LastName_UK: "Henry Yarburgh Everitt ",
  //     city_UK: "Brighton",
  //     Island: "Antigua",
  //     people_enslaved: 176,
  //     compensation: 2734,
  //     latitude: 50.824996,
  //     longitude: -0.14285,
  //   },
  //   {
  //     id: 37,
  //     FirstName_LastName_UK: "Archibald MacDonald ",
  //     city_UK: "Brighton",
  //     Island: "St Vincent",
  //     people_enslaved: 610,
  //     compensation: 15765,
  //     latitude: 50.8172686,
  //     longitude: -0.1174275,
  //   },
  //   {
  //     id: 38,
  //     FirstName_LastName_UK: "John Brome ",
  //     city_UK: "Brighton",
  //     Island: "Barbados",
  //     people_enslaved: 285,
  //     compensation: 6542,
  //     latitude: 50.8249099,
  //     longitude: -0.159461,
  //   },
  //   {
  //     id: 39,
  //     FirstName_LastName_UK: "John Dawkins ",
  //     city_UK: "Brighton",
  //     Island: "Jamaica",
  //     people_enslaved: 246,
  //     compensation: 4668,
  //     latitude: 50.8145597,
  //     longitude: -0.1081976,
  //   },
  //   {
  //     id: 40,
  //     FirstName_LastName_UK: "John Eldad Walters ",
  //     city_UK: "Brighton",
  //     Island: "Jamaica",
  //     people_enslaved: 916,
  //     compensation: 16142,
  //     latitude: 50.8197701,
  //     longitude: -0.1254411,
  //   },
  //   {
  //     id: 41,
  //     FirstName_LastName_UK: "John Henry Noding ",
  //     city_UK: "Brighton",
  //     Island: "Tobago",
  //     people_enslaved: 118,
  //     compensation: 2800,
  //     latitude: 50.825742,
  //     longitude: -0.142434,
  //   },
  //   {
  //     id: 42,
  //     FirstName_LastName_UK: "John Laing ",
  //     city_UK: "Brighton",
  //     Island: "Jamaica",
  //     people_enslaved: 57,
  //     compensation: 1164,
  //     latitude: 50.8265146,
  //     longitude: -0.1520861,
  //   },
  //   {
  //     id: 43,
  //     FirstName_LastName_UK: "John Roach Bovell and John Matthews Boswell junior",
  //     city_UK: "Brighton",
  //     Island: "British Guiana",
  //     people_enslaved: 392,
  //     compensation: 20820,
  //     latitude: 50.828287,
  //     longitude: -0.141603,
  //   },
  //   {
  //     id: 44,
  //     FirstName_LastName_UK: "Louisa Barry ",
  //     city_UK: "Brighton",
  //     Island: "British Guiana",
  //     people_enslaved: 108,
  //     compensation: 5813,
  //     latitude: " 50.828653",
  //     longitude: -0.141294,
  //   },
  //   {
  //     id: 45,
  //     FirstName_LastName_UK: "Mary Chandler ",
  //     city_UK: "Brighton",
  //     Island: "Jamaica",
  //     people_enslaved: 322,
  //     compensation: 5849,
  //     latitude: 50.8166144,
  //     longitude: -0.147456,
  //   },
  //   {
  //     id: 46,
  //     FirstName_LastName_UK: "Mary Johnson (née Francis) ",
  //     city_UK: "Brighton",
  //     Island: "Antigua",
  //     people_enslaved: 264,
  //     compensation: 3461,
  //     latitude: " 50.824364",
  //     longitude: " -0.143171",
  //   },
  //   {
  //     id: 47,
  //     FirstName_LastName_UK: "Philip Laycock Story ",
  //     city_UK: "Brighton",
  //     Island: "Montserrat",
  //     people_enslaved: 128,
  //     compensation: 1977,
  //     latitude: 50.8177347,
  //     longitude: -0.1101429,
  //   },
  //   {
  //     id: 48,
  //     FirstName_LastName_UK: "Ralph Rice ",
  //     city_UK: "Brighton",
  //     Island: "Jamaica",
  //     people_enslaved: 191,
  //     compensation: 3579,
  //     latitude: 50.8183453,
  //     longitude: -0.1253383,
  //   },
  //   {
  //     id: 49,
  //     FirstName_LastName_UK: "Richard Alexander Oswald ",
  //     city_UK: "Brighton",
  //     Island: "Jamaica",
  //     people_enslaved: 297,
  //     compensation: 5445,
  //     latitude: 50.826829,
  //     longitude: -0.141971,
  //   },
  //   {
  //     id: 50,
  //     FirstName_LastName_UK: "Richard Barnes Bell ",
  //     city_UK: "Brighton",
  //     Island: "Mauritius",
  //     people_enslaved: 19,
  //     compensation: 632,
  //     latitude: 50.8198916,
  //     longitude: -0.1370037,
  //   },
  //   {
  //     id: 51,
  //     FirstName_LastName_UK: "Richard Silvester Cahill",
  //     city_UK: "Brighton",
  //     Island: "Trinidad",
  //     people_enslaved: 131,
  //     compensation: 3769,
  //     latitude: 50.825402,
  //     longitude: -0.142655,
  //   },
  //   {
  //     id: 52,
  //     FirstName_LastName_UK: "Robert Home Gordon ",
  //     city_UK: "Brighton",
  //     Island: "Jamaica",
  //     people_enslaved: "No Data",
  //     compensation: "No Data",
  //     latitude: 50.827318,
  //     longitude: -0.141854,
  //   },
  //   {
  //     id: 53,
  //     FirstName_LastName_UK:
  //       "Samuel Anderson and Anna Rebecca Anderson (née Ruthven)",
  //     city_UK: "Brighton",
  //     Island: "Jamaica",
  //     people_enslaved: 252,
  //     compensation: 4866,
  //     latitude: 50.8247482,
  //     longitude: -0.1531025,
  //   },
  //   {
  //     id: 54,
  //     FirstName_LastName_UK: "Thomas Martin ",
  //     city_UK: "Brighton",
  //     Island: "Jamaica",
  //     people_enslaved: 50,
  //     compensation: 1075,
  //     latitude: 50.8258599,
  //     longitude: -0.151302236,
  //   },
  //   {
  //     id: 55,
  //     FirstName_LastName_UK: "Thomson Hankey ",
  //     city_UK: "Brighton",
  //     Island: "Grenada 445 (Tempe Estate)",
  //     people_enslaved: 1919,
  //     compensation: 49706,
  //     latitude: 50.8239702,
  //     longitude: -0.1584867,
  //   },
  //   {
  //     id: 56,
  //     FirstName_LastName_UK: "Letitia Taylor (née Nembhard)",
  //     city_UK: "No Data",
  //     people_enslaved: "No Data",
  //     compensation: "No Data",
  //     latitude: 50.81648,
  //     longitude: -0.115245,
  //   },
  //   {
  //     id: 57,
  //     FirstName_LastName_UK: "Edward Lumley Wilson",
  //     city_UK: "St Kitts 440 (Stone Fort)",
  //     people_enslaved: 161,
  //     compensation: 2678,
  //     latitude: 50.8198343,
  //     longitude: -0.1333396,
  //   },
  //   {
  //     id: 58,
  //     FirstName_LastName_UK: "Robert French Kirwan",
  //     city_UK: "Montserrat 35",
  //     people_enslaved: 2,
  //     compensation: 50,
  //     latitude: 50.8205,
  //     longitude: -0.1363,
  //   },
  //   {
  //     id: 59,
  //     FirstName_LastName_UK: "William Williams Blake",
  //     city_UK: "Jamaica Westmoreland 29 (Shrewsbury)",
  //     people_enslaved: 329,
  //     compensation: "£545 4",
  //     latitude: 50.8218675,
  //     longitude: -0.1511411,
  //   },
  //   {
  //     id: 60,
  //     FirstName_LastName_UK: "Alexander Maximilien Touzalin",
  //     city_UK: "Jamaica Westmoreland 591",
  //     people_enslaved: 5,
  //     compensation: 93,
  //     latitude: 50.822841,
  //     longitude: -0.148312,
  //   },
  //   {
  //     id: 61,
  //     FirstName_LastName_UK: "William Augustus Parker",
  //     city_UK: "British Guiana 1475",
  //     people_enslaved: 88,
  //     compensation: 4500,
  //   },
  //   {
  //     id: 62,
  //     FirstName_LastName_UK: "William 'King' Mitchell",
  //     city_UK: "Antigua 38 (Marble Hill)",
  //     people_enslaved: 199,
  //     compensation: 2482,
  //     latitude: 50.823664,
  //     longitude: -0.153362,
  //   },
  //   {
  //     id: 63,
  //     FirstName_LastName_UK: "Katherine Ann Hinds Cobham (née Skinner)",
  //     city_UK: "No Data",
  //     people_enslaved: "No Data",
  //     compensation: "No Data",
  //     latitude: 50.824,
  //     longitude: -0.1536,
  //   },
  //   {
  //     id: 64,
  //     FirstName_LastName_UK: "John Cockerell",
  //     city_UK: "Mauritius 2788",
  //     people_enslaved: 79,
  //     compensation: 2444,
  //     latitude: 50.8244792,
  //     longitude: -0.1621662,
  //   },
  //   {
  //     id: 65,
  //     FirstName_LastName_UK: "Agnes Joanna Darlot (née Troup)",
  //     city_UK: "No Data",
  //     people_enslaved: "No Data",
  //     compensation: "No Data",
  //     latitude: 50.8247807,
  //     longitude: -0.1519241,
  //   },
  //   {
  //     id: 66,
  //     FirstName_LastName_UK: "Joshua Kentish",
  //     city_UK: "Antigua 617 (Town of St John)",
  //     people_enslaved: 32,
  //     compensation: 550,
  //     latitude: 50.826,
  //     longitude: -0.155,
  //   },
  //   {
  //     id: 67,
  //     FirstName_LastName_UK: "Skeffington Robinson",
  //     city_UK: "Dominica 581A & B (Rosalie)",
  //     people_enslaved: 181,
  //     compensation: 3488,
  //     latitude: 50.826041,
  //     longitude: -0.155044,
  //   },
  //   {
  //     id: 68,
  //     FirstName_LastName_UK: "John Matthews Boswell junior",
  //     city_UK: "No Data",
  //     people_enslaved: "No Data",
  //     compensation: "No Data",
  //     latitude: 50.8295,
  //     longitude: -0.1354,
  //   },
  //   {
  //     id: 69,
  //     FirstName_LastName_UK: "Sarah Mary Barker Lowdell (née Boswell)",
  //     city_UK: "No Data",
  //     people_enslaved: "No Data",
  //     compensation: "No Data",
  //     latitude: 50.8295,
  //     longitude: -0.1344,
  //   },
  //   {
  //     id: 70,
  //     FirstName_LastName_UK: "Sarah Coppard Previously Boswell (née Saxby)",
  //     latitude: 50.8336,
  //     longitude: -0.1364,
  //   },
  //   {
  //     id: 71,
  //     FirstName_LastName_UK: "Alexander Purcell Anderson",
  //     city_UK: "Brighton",
  //     people_enslaved: "No Data",
  //     compensation: "No Data",
  //     latitude: 50.827318,
  //     longitude: -0.141864,
  //   },
  //   {
  //     id: 72,
  //     FirstName_LastName_UK: "Dorothy Diana Yates (née Smellie)",
  //     city_UK: "Jamaica Kingston 1943",
  //     people_enslaved: 10,
  //     compensation: 169,
  //     latitude: 50.81648,
  //     longitude: -0.141874,
  //   },
  //   {
  //     id: 73,
  //     FirstName_LastName_UK: "Elizabeth Stewart or Stuart formerly McLachlan",
  //     city_UK: "Brighton",
  //     people_enslaved: "No Data",
  //     compensation: "No Data",
  //     latitude: 50.8198343,
  //     longitude: -0.141884,
  //   },
  //   {
  //     id: 74,
  //     FirstName_LastName_UK: "George Baillie Previous owner (non-claimant)",
  //     city_UK: "Brighton",
  //     people_enslaved: "No Data",
  //     compensation: "No Data",
  //     latitude: 50.8205,
  //     longitude: -0.141894,
  //   },
  //   {
  //     id: 75,
  //     FirstName_LastName_UK: "James Phyn",
  //     city_UK: "Brighton",
  //     people_enslaved: "No Data",
  //     compensation: "No Data",
  //     latitude: 50.8218675,
  //     longitude: -0.141904,
  //   },
  //   {
  //     id: 76,
  //     FirstName_LastName_UK: "John Ingram senior",
  //     city_UK: "Brighton",
  //     people_enslaved: "No Data",
  //     compensation: "No Data",
  //     latitude: 50.822841,
  //     longitude: -0.141914,
  //   },
  //   {
  //     id: 77,
  //     FirstName_LastName_UK: "Margaret Still Mavor",
  //     city_UK: "Brighton",
  //     people_enslaved: "No Data",
  //     compensation: "No Data",
  //     latitude: 50.8232106,
  //     longitude: -0.141924,
  //   },
  //   {
  //     id: 78,
  //     FirstName_LastName_UK: "Mary Ruthven (née Virgo)",
  //     city_UK: "Brighton",
  //     people_enslaved: "No Data",
  //     compensation: "No Data",
  //     latitude: 50.823664,
  //     longitude: -0.141934,
  //   },
  //   {
  //     id: 79,
  //     FirstName_LastName_UK: "Nathaniel Bogle French senior",
  //     city_UK: "Brighton",
  //     people_enslaved: "No Data",
  //     compensation: "No Data",
  //     latitude: 50.824,
  //     longitude: -0.141944,
  //   },
  //   {
  //     id: 80,
  //     FirstName_LastName_UK: "Robert Alexander Lambert RN",
  //     city_UK: "Brighton",
  //     people_enslaved: "No Data",
  //     compensation: "No Data",
  //     latitude: 50.8244792,
  //     longitude: -0.141954,
  //   },
  //   {
  //     id: 81,
  //     FirstName_LastName_UK: "Robert Home Gordon",
  //     city_UK: "Brighton",
  //     people_enslaved: "No Data",
  //     compensation: "No Data",
  //     latitude: 50.8247807,
  //     longitude: -0.141964,
  //   },
  //   {
  //     id: 82,
  //     FirstName_LastName_UK: "Susanna Harriot Gordon (née Hope)",
  //     city_UK: "Jamaica St Ann 498 (Home Castle Estate)",
  //     people_enslaved: 798,
  //     compensation: 15945,
  //     latitude: 50.826,
  //     longitude: -0.141974,
  //   },
  //   {
  //     id: 83,
  //     FirstName_LastName_UK: "Thomas Nevill",
  //     city_UK: "Brighton",
  //     compensation: "No Data",
  //     latitude: 50.826041,
  //     longitude: -0.141974,
  //   },
  //   {
  //     id: 84,
  //     FirstName_LastName_UK: "Thomas Scott Reignolds",
  //     city_UK: "Jamaica St Thomas-in-the-Vale 294 (Hyde Estate)",
  //     people_enslaved: 147,
  //     compensation: 2660,
  //     latitude: 50.8295,
  //     longitude: -0.141984,
  //   },
  //   {
  //     id: 85,
  //     FirstName_LastName_UK: "Robert Allen",
  //     city_UK: "No data",
  //     Island: "Barcombe",
  //     people_enslaved: "East Sussex",
  //     compensation: "No data",
  //     latitude: 50.9325232,
  //     longitude: 0.0298005,
  //   },
  //   {
  //     id: 86,
  //     FirstName_LastName_UK: "Louise Scarlett",
  //     city_UK: "2 Lansdowne Terrace (partial)",
  //     Island: "East Lewes",
  //     people_enslaved: "Sussex",
  //     compensation: "No data",
  //     latitude: 50.8746139,
  //     longitude: 0.0051153,
  //   },
  //   {
  //     id: 87,
  //     FirstName_LastName_UK: "Richard Watt Walker",
  //     city_UK: "Tilgate Forest Lodge",
  //     Island: "Pease Pottage, Crawley",
  //     people_enslaved: "Sussex",
  //     compensation: "RH11 9AF",
  //     latitude: 51.072791,
  //     longitude: -0.200333,
  //   },
  //   {
  //     id: 88,
  //     FirstName_LastName_UK: "Samuel Jeffries",
  //     city_UK: "Pixton House, Forest Row",
  //     Island: "East Grinstead,",
  //     people_enslaved: "Sussex",
  //     compensation: "RH18 5JX",
  //     latitude: 51.100045,
  //     longitude: 0.051609,
  //   },
  //   {
  //     id: 89,
  //     FirstName_LastName_UK: "Henry Shirley III",
  //     city_UK: "Pippinford Lodge (Manor)",
  //     Island: "near East Grinstead,",
  //     people_enslaved: "Sussex",
  //     compensation: "TN22 3HW",
  //     latitude: 51.057329,
  //     longitude: 0.054371,
  //   },
  //   {
  //     id: 90,
  //     FirstName_LastName_UK: "Jonathan Worrell",
  //     city_UK: "(Partial)",
  //     Island: "Frampost",
  //     people_enslaved: "Sussex",
  //     compensation: "RH19 4ND",
  //     latitude: 51.109592,
  //     longitude: -0.016494,
  //   },
  //   {
  //     id: 91,
  //     FirstName_LastName_UK: "Jonathan Worrell",
  //     city_UK: "(Partial)",
  //     Island: "Frampost",
  //     people_enslaved: "Sussex",
  //     compensation: "RH19 4ND",
  //     latitude: 51.109626,
  //     longitude: -0.016545,
  //   },
  //   {
  //     id: 92,
  //     FirstName_LastName_UK: "Jonathan Worrell",
  //     city_UK: "(Partial)",
  //     Island: "Frampost",
  //     people_enslaved: "Sussex",
  //     compensation: "RH19 4ND",
  //     latitude: 51.109606,
  //     longitude: -0.016807,
  //   },
  //   {
  //     id: 93,
  //     FirstName_LastName_UK: "Anne Dalzell Thomson",
  //     city_UK: "Albourne Place",
  //     Island: "Albourne",
  //     people_enslaved: "Sussex",
  //     compensation: "BN6 9DU",
  //     latitude: 50.929866,
  //     longitude: -0.219119,
  //   },
  //   {
  //     id: 94,
  //     FirstName_LastName_UK: "Anne Dalzell Thomson",
  //     city_UK: "Albourne Place",
  //     Island: "Albourne",
  //     people_enslaved: "Sussex",
  //     compensation: "BN6 9DU",
  //     latitude: 50.929795,
  //     longitude: -0.219303,
  //   },
  //   {
  //     id: 95,
  //     FirstName_LastName_UK: "George Elliott Clarke",
  //     city_UK: "(Partial)",
  //     Island: "Frampost",
  //     people_enslaved: "Sussex",
  //     compensation: "RH19 4ND",
  //     latitude: 51.109776,
  //     longitude: -0.017747,
  //   },
  //   {
  //     id: 96,
  //     FirstName_LastName_UK: "John Trayton Fuller",
  //     city_UK: "(Partial)",
  //     Island: "East Grinstead",
  //     people_enslaved: "Sussex",
  //     compensation: "No data",
  //     latitude: 51.132218,
  //     longitude: -0.011766,
  //   },
  //   {
  //     id: 97,
  //     FirstName_LastName_UK: "Abraham Cumberbatch Sober",
  //     city_UK: "(Partial)",
  //     Island: "Lewes",
  //     people_enslaved: "Sussex",
  //     compensation: "No data",
  //     latitude: 50.874614,
  //     longitude: 0.005115,
  //   },
];
